"""model: building

Revision ID: 1eae540eaffc
Revises: 3e68c64bdcbe
Create Date: 2026-06-07 14:36:44.139546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1eae540eaffc"
down_revision: Union[str, Sequence[str], None] = "3e68c64bdcbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=150), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
    )
    op.create_table(
        "rooms",
        sa.Column("room_number", sa.String(length=10), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "room_type",
            postgresql.ENUM(
                "lecture",
                "seminar",
                "laboratory",
                "computer_class",
                "common_class",
                "gym",
                name="room_type",
            ),
            nullable=False,
        ),
        sa.Column("building_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "capacity > 0", name=op.f("ck_rooms_capacity_check")
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.id"],
            name=op.f("fk_rooms_building_id_buildings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rooms")),
        sa.UniqueConstraint(
            "building_id", "room_number", name="unique_room_per_building"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    op.drop_table("buildings")
    # ### end Alembic commands ###
