"""model: practice

Revision ID: 24a399127bc8
Revises: fae8c2af6632
Create Date: 2026-06-08 21:00:44.782137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24a399127bc8"
down_revision: Union[str, Sequence[str], None] = "fae8c2af6632"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "practices",
        sa.Column("semester_id", sa.UUID(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "educational",
                "production",
                "pre_graduate",
                name="practice_type",
            ),
            nullable=False,
        ),
        sa.Column("practice_start_date", sa.Date(), nullable=False),
        sa.Column("practice_end_date", sa.Date(), nullable=False),
        sa.Column("hours", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "hours > 0 AND hours <= 1000",
            name=op.f("ck_practices_ck_practice_hours_range"),
        ),
        sa.CheckConstraint(
            "practice_start_date < practice_end_date",
            name=op.f("ck_practices_ck_practice_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["semester_id"],
            ["semesters.id"],
            name=op.f("fk_practices_semester_id_semesters"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practices")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("practices")
    # ### end Alembic commands ###
    sa.Enum(name="practice_type").drop(op.get_bind(), checkfirst=True)
