"""add mixins: teacher

Revision ID: 6ff92647e050
Revises: 9018cde120f4
Create Date: 2026-06-18 15:32:31.245058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "6ff92647e050"
down_revision: Union[str, Sequence[str], None] = "9018cde120f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teacher_availability",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "teacher_availability",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "teacher_availability",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "teacher_availability",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_teacher_availability_updated_by_users"),
        "teacher_availability",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_teacher_availability_created_by_users"),
        "teacher_availability",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "teacher_substitutions",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "teacher_substitutions",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "teacher_substitutions",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_teacher_substitutions_created_by_users"),
        "teacher_substitutions",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_teacher_substitutions_updated_by_users"),
        "teacher_substitutions",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "teachers",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "teachers",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_teachers_updated_by_users"),
        "teachers",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_teachers_created_by_users"),
        "teachers",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_teachers_created_by_users"), "teachers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_teachers_updated_by_users"), "teachers", type_="foreignkey"
    )
    op.drop_column("teachers", "updated_by")
    op.drop_column("teachers", "updated_at")
    op.drop_column("teachers", "created_by")
    op.drop_column("teachers", "created_at")
    op.drop_constraint(
        op.f("fk_teacher_substitutions_updated_by_users"),
        "teacher_substitutions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_teacher_substitutions_created_by_users"),
        "teacher_substitutions",
        type_="foreignkey",
    )
    op.drop_column("teacher_substitutions", "updated_by")
    op.drop_column("teacher_substitutions", "updated_at")
    op.drop_column("teacher_substitutions", "created_by")
    op.drop_constraint(
        op.f("fk_teacher_availability_created_by_users"),
        "teacher_availability",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_teacher_availability_updated_by_users"),
        "teacher_availability",
        type_="foreignkey",
    )
    op.drop_column("teacher_availability", "updated_by")
    op.drop_column("teacher_availability", "updated_at")
    op.drop_column("teacher_availability", "created_by")
    op.drop_column("teacher_availability", "created_at")
    # ### end Alembic commands ###
