"""add mixins: schedule

Revision ID: 6c6d6be5a8af
Revises: 48948522b0be
Create Date: 2026-06-18 15:16:34.556128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "6c6d6be5a8af"
down_revision: Union[str, Sequence[str], None] = "48948522b0be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule_items",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "schedule_items",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "schedule_items",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_schedule_items_updated_by_users"),
        "schedule_items",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_schedule_items_created_by_users"),
        "schedule_items",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "schedule_plans",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "schedule_plans",
        sa.Column(
            "created_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.add_column(
        "schedule_plans",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "schedule_plans",
        sa.Column(
            "updated_by",
            fastapi_users_db_sqlalchemy.generics.GUID(),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_schedule_plans_updated_by_users"),
        "schedule_plans",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_schedule_plans_created_by_users"),
        "schedule_plans",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_schedule_plans_created_by_users"),
        "schedule_plans",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_schedule_plans_updated_by_users"),
        "schedule_plans",
        type_="foreignkey",
    )
    op.drop_column("schedule_plans", "updated_by")
    op.drop_column("schedule_plans", "updated_at")
    op.drop_column("schedule_plans", "created_by")
    op.drop_column("schedule_plans", "created_at")
    op.drop_constraint(
        op.f("fk_schedule_items_created_by_users"),
        "schedule_items",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_schedule_items_updated_by_users"),
        "schedule_items",
        type_="foreignkey",
    )
    op.drop_column("schedule_items", "updated_by")
    op.drop_column("schedule_items", "updated_at")
    op.drop_column("schedule_items", "created_by")
    # ### end Alembic commands ###
