__all__ = (
    "UserRead",
    "UserCreate",
    "UserUpdate",
    "BaseSchema",
    "BuildingBase",
    "BuildingResponse",
    "BuildingCreate",
    "BuildingUpdate",
    "BuildingBrief",
    "RoomCreate",
    "RoomUpdate",
    "RoomBase",
    "RoomResponse",
    "RoomListResponse",
    "RoomBrief",
    "GroupBase",
    "GroupResponse",
    "GroupListResponse",
    "GroupCreate",
    "GroupUpdate",
    "GroupBrief",
    "TeacherBase",
    "TeacherResponse",
    "TeacherBrief",
    "TeacherListResponse",
    "TeacherDetailResponse",
    "TeacherCreate",
    "TeacherUpdateByTeacher",
    "TeacherUpdateByAdmin",
    "SubjectResponse",
    "SubjectDetailResponse",
    "SubjectBase",
    "SubjectListResponse",
    "SubjectBrief",
    "SubjectUpdate",
    "SubjectCreate",
    "TeacherAvailabilityResponse",
    "TeacherAvailabilityBase",
    "TeacherAvailabilityListResponse",
    "TeacherAvailabilityUpdate",
    "TeacherAvailabilityCreate",
    "TeacherAvailabilityBrief",
)

from .user import UserRead, UserCreate, UserUpdate
from .base import BaseSchema
from .building_and_room.building import (
    BuildingBase,
    BuildingResponse,
    BuildingCreate,
    BuildingUpdate,
    BuildingBrief,
)
from .building_and_room.room import (
    RoomCreate,
    RoomUpdate,
    RoomBase,
    RoomResponse,
    RoomListResponse,
    RoomBrief,
)
from .group import (
    GroupBase,
    GroupResponse,
    GroupListResponse,
    GroupCreate,
    GroupUpdate,
    GroupBrief,
)
from .teacher_and_subject.teacher import (
    TeacherBase,
    TeacherResponse,
    TeacherBrief,
    TeacherListResponse,
    TeacherDetailResponse,
    TeacherCreate,
    TeacherUpdateByTeacher,
    TeacherUpdateByAdmin,
)
from .teacher_and_subject.subject import (
    SubjectResponse,
    SubjectDetailResponse,
    SubjectBase,
    SubjectListResponse,
    SubjectBrief,
    SubjectUpdate,
    SubjectCreate,
)
from .teacher_and_subject.teacher_availability import (
    TeacherAvailabilityResponse,
    TeacherAvailabilityBase,
    TeacherAvailabilityListResponse,
    TeacherAvailabilityUpdate,
    TeacherAvailabilityCreate,
    TeacherAvailabilityBrief,
)
